url: "https://andreivladescu.github.io"
author: "Andrei Vladescu"
description: "Hardware security · Embedded systems · Reverse engineering"
github_username: "AndreiVladescu"
email: "avladescu2000@gmail.com"
